# .travis.yml
language: php
sudo: false
php: 
  - 5.5.9

script:
  #A few test cases
  - echo "tested"

  before_deploy:
  - mkdir build
  - cp README.md build
  - cp plugin.php build
 
deploy:
  - provider: wordpress-plugin
    on:
      php: 5.5.9
      repo: plugin
    username: ch12jan1998@gmail.com
    password: MyPassword
    build_dir: build 
