# .travis.yml
 
language: php
 
sudo: false
 
php:
  - 7.0
  - 7.1
  - 5.5.9
 
script:
  # Run your tests here.
  - echo 'Tested'
  
  before_deploy:
  - mkdir build
  - cp LICENSE build
  - cp README.txt build
  - cp remove-medium-cross-links.php build
 
deploy:
  - provider: wordpress-plugin
    edge:
      source: TypistTech/dpl
      branch: add-wordpress-plugin-deployment
    on:
      php: 5.5.9
      tags: true
      repo: plugin
    slug: remove-medium-cross-links
    username: charan05
    password: $WORDPRESS_ORG_PASSWORD
    build_dir: build 
