# .travis.yml
language: php
sudo: false
php: 
  - 5.5.9

script:
  #A few test cases
  - echo "tested"

  before_deploy:
  - mkdir build
  - cp README.md build
  - cp plugin.php buld
 
deploy:
  - provider: wordpress-plugin
    on:
      php: 5.5.9
      tags: true
      repo: plugin
    username: charan
    password: *****
    build_dir: build 
